baseURL: 'https://denniskniep.github.io/'
languageCode: 'en-us'
theme: "PaperMod"
paginate: 10
menu:
    main:
        - name: Home
          url: /
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Posts
          url: posts/
          weight: 10

markup:
  goldmark:
    parser:
      attribute:
        block: true
        title: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
params:
    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120

    homeInfoParams:
        Title: Hi there 👋
        Content: Writing here about Security, FIDO, Software Development & more
        buttons:
          - name: Archive
            url: "/archive"
          - name: Github
            url: "https://github.com/"
    socialIcons: 
      - name: "github"
        url: "https://github.com/denniskniep"
      - name: "twitter"
        url: "https://twitter.com/dennis_kniep"
      - name: "mastodon"
        url: "https://infosec.exchange/@dennis_kniep"        
      - name: Rss
        url: "index.xml"
    ShowBreadCrumbs: true
    ShowShareButtons: true
    ShowReadingTime: true
    ShowPostNavLinks: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    ShowCodeCopyButtons: true
    cover:
        responsiveImages: false
        linkFullImages: true